#!/usr/bin/env ruby

##
#
#  @project CodeChallenger CLI
#  @author  Matti van de Weem <mvdweem@gmail.com>, Koen Vendrik <k.vendrik@gmail.com>
#  @date    January 2015
#  @url     http://github.com/CodeChallenger
#
##

require 'rubygems'
require 'bundler/setup'

require 'optparse'
require 'json'
require_relative 'inc/challenger.class.rb'


# read a file
def read_file(file_name)
  file = File.open(file_name, 'r')
  data = file.read
  file.close
  return data
end

# hash to store command line options
options = {}

helpText = <<HELP
Usage: codechallenger <command> [options...]

Commands:
  init          generate a new challenge
  deploy        deploys your challenge code to Github

See 'codechallenger <command> --help' for help on a specific command.
HELP

global = OptionParser.new do |opts|
  opts.on('-h', '--help', 'Show help') do |language|
    puts helpText
    exit 0
  end
end

subCommands = {

    'init' => {
        :optionParser => OptionParser.new do |opts|
          opts.banner = 'Usage: codechallenger init [options...]'

          opts.on('--language [LANGUAGE]', 'Give a challenge for given language') do |language|
            options[:language] = language.downcase
          end

          opts.on('--framework [FRAMEWORK]', 'Give a challenge with the given framework') do |framework|
            options[:framework] = framework.downcase
          end

          opts.on('--path [PATH]', 'Path to folder you\'d like to create the challenge in') do |path|
            options[:path] = path
          end
        end,
        :handler => lambda {
          path = options[:path] != nil ? options[:path]+'/.codechallenger.json' : '.codechallenger.json'

          if File.file?(path)
            loop do
              print "\nThere is already a .codechallenger.json in this directory.\nWould you like to continue? [y/N] "

              answer = gets.chomp
              return if answer.downcase != 'y'
              break if answer.downcase == 'y'
            end
          end

          challenger = Challenger.new(options)

          loop do
            challenger.new_challenge
            puts "\n"+challenger.construct_str
            print "\nUse this challenge? [Y/n] "

            answer = gets.chomp
            break if answer.downcase != 'n'
          end

          details = challenger.get_details

          # write details to .codechallenger.json file
          File.open(path, 'w') {|f| f.write(details.to_json) }

          puts "\n✔ Start Coding!"
        }
    },

    'deploy' => {
        :optionParser => OptionParser.new do |opts|
          opts.banner = 'Usage: codechallenger deploy'

          opts.on('--path [PATH]', 'Path to the challenge folder') do |path|
            options[:path] = path
          end
        end,
        :handler => lambda {
          path = options[:path] != nil ? options[:path]+'/' : ''

          if not File.exists?(path+'.codechallenger.json')
            puts 'No .codechallenger.json file found.'
            exit 1
          end

          if not File.directory?(path+'.git')
            `git init`
          end

          settings = File.read(path+'.codechallenger.json', 'r')
          p settings

          if not settings['repository']
            loop do
              print "\nEnter the URL of the repository you\'d like to store your challenge in: "
              answer = gets.chomp
              break if answer != ''
            end

            `git remote add codechallenger `+answer

            settings['repository'] = answer
          end

          p 'Done...'
        }
    }

}

# parse global flags
global.order!

# if subcommand, parse flags
command = ARGV.shift
if command != nil && subCommands[command] != nil
  details = subCommands[command]
  details[:optionParser].order!
  details[:handler].call
else
  puts helpText
end

exit 0
